# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/spotify-completist',
                'doc_host': 'https://januff.github.io',
                'git_url': 'https://github.com/januff/spotify-completist',
                'lib_path': 'spotify_completist'},
  'syms': {'spotify_completist.core': {'spotify_completist.core.foo': ('core.html#foo', 'spotify_completist/core.py')}}}
